header:
  seq: 0
  stamp:
    secs: 1567240304
    nsecs: 0
  frame_id: novatel
child_frame_id: livox_front
transform:
  translation:
    x: 0.0632849
    y: 1.73202
    z: -0.0587026
  rotation:
    x: 0.0191163
    y: -0.0118181
    z: 0.702294
    w: 0.711532