// Generated by gencpp from file roscpp_tutorials/Box2d.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_BOX2D_H
#define ROSCPP_TUTORIALS_MESSAGE_BOX2D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct Box2d_
{
  typedef Box2d_<ContainerAllocator> Type;

  Box2d_()
    : x(0)
    , y(0)
    , w(0)
    , h(0)  {
    }
  Box2d_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , w(0)
    , h(0)  {
  (void)_alloc;
    }



   typedef int64_t _x_type;
  _x_type x;

   typedef int64_t _y_type;
  _y_type y;

   typedef int64_t _w_type;
  _w_type w;

   typedef int64_t _h_type;
  _h_type h;





  typedef boost::shared_ptr< ::roscpp_tutorials::Box2d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::Box2d_<ContainerAllocator> const> ConstPtr;

}; // struct Box2d_

typedef ::roscpp_tutorials::Box2d_<std::allocator<void> > Box2d;

typedef boost::shared_ptr< ::roscpp_tutorials::Box2d > Box2dPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::Box2d const> Box2dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::Box2d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::Box2d_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::Box2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::Box2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::Box2d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::Box2d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::Box2d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::Box2d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::Box2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a851d579940455fce56778da08b6298f";
  }

  static const char* value(const ::roscpp_tutorials::Box2d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa851d579940455fcULL;
  static const uint64_t static_value2 = 0xe56778da08b6298fULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::Box2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/Box2d";
  }

  static const char* value(const ::roscpp_tutorials::Box2d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::Box2d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "  int64 x\n\
  int64 y\n\
  int64 w\n\
  int64 h\n\
";
  }

  static const char* value(const ::roscpp_tutorials::Box2d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::Box2d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.w);
      stream.next(m.h);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Box2d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::Box2d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::Box2d_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int64_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int64_t>::stream(s, indent + "  ", v.y);
    s << indent << "w: ";
    Printer<int64_t>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<int64_t>::stream(s, indent + "  ", v.h);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_BOX2D_H
