// Generated by gencpp from file roscpp_tutorials/Box3d.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_BOX3D_H
#define ROSCPP_TUTORIALS_MESSAGE_BOX3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roscpp_tutorials/Point3d.h>

namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct Box3d_
{
  typedef Box3d_<ContainerAllocator> Type;

  Box3d_()
    : position()
    , l(0.0)
    , w(0.0)
    , h(0.0)  {
    }
  Box3d_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , l(0.0)
    , w(0.0)
    , h(0.0)  {
  (void)_alloc;
    }



   typedef  ::roscpp_tutorials::Point3d_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef float _l_type;
  _l_type l;

   typedef float _w_type;
  _w_type w;

   typedef float _h_type;
  _h_type h;





  typedef boost::shared_ptr< ::roscpp_tutorials::Box3d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::Box3d_<ContainerAllocator> const> ConstPtr;

}; // struct Box3d_

typedef ::roscpp_tutorials::Box3d_<std::allocator<void> > Box3d;

typedef boost::shared_ptr< ::roscpp_tutorials::Box3d > Box3dPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::Box3d const> Box3dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::Box3d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::Box3d_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::Box3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::Box3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::Box3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::Box3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::Box3d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::Box3d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::Box3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a34d4ccdf2dd022a68abd8ac63caa76";
  }

  static const char* value(const ::roscpp_tutorials::Box3d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a34d4ccdf2dd022ULL;
  static const uint64_t static_value2 = 0xa68abd8ac63caa76ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::Box3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/Box3d";
  }

  static const char* value(const ::roscpp_tutorials::Box3d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::Box3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "  Point3d position\n\
  float32 l\n\
  float32 w\n\
  float32 h\n\
\n\
================================================================================\n\
MSG: roscpp_tutorials/Point3d\n\
	float32 x  # in meters or m/s\n\
	float32 y  # in meters or m/s\n\
	float32 z  # height in meters or m/s\n\
";
  }

  static const char* value(const ::roscpp_tutorials::Box3d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::Box3d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.l);
      stream.next(m.w);
      stream.next(m.h);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Box3d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::Box3d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::Box3d_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::roscpp_tutorials::Point3d_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "l: ";
    Printer<float>::stream(s, indent + "  ", v.l);
    s << indent << "w: ";
    Printer<float>::stream(s, indent + "  ", v.w);
    s << indent << "h: ";
    Printer<float>::stream(s, indent + "  ", v.h);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_BOX3D_H
