// Generated by gencpp from file roscpp_tutorials/CameraDetection.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_CAMERADETECTION_H
#define ROSCPP_TUTORIALS_MESSAGE_CAMERADETECTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roscpp_tutorials/MsgHeader.h>
#include <roscpp_tutorials/Detection.h>

namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct CameraDetection_
{
  typedef CameraDetection_<ContainerAllocator> Type;

  CameraDetection_()
    : header()
    , detections()
    , sensor_id()  {
    }
  CameraDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detections(_alloc)
    , sensor_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::roscpp_tutorials::MsgHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::roscpp_tutorials::Detection_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::roscpp_tutorials::Detection_<ContainerAllocator> >::other >  _detections_type;
  _detections_type detections;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sensor_id_type;
  _sensor_id_type sensor_id;





  typedef boost::shared_ptr< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> const> ConstPtr;

}; // struct CameraDetection_

typedef ::roscpp_tutorials::CameraDetection_<std::allocator<void> > CameraDetection;

typedef boost::shared_ptr< ::roscpp_tutorials::CameraDetection > CameraDetectionPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::CameraDetection const> CameraDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::CameraDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45e456a3cb7c718bba8b29376a0e7153";
  }

  static const char* value(const ::roscpp_tutorials::CameraDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45e456a3cb7c718bULL;
  static const uint64_t static_value2 = 0xba8b29376a0e7153ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/CameraDetection";
  }

  static const char* value(const ::roscpp_tutorials::CameraDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MsgHeader header\n\
Detection[] detections\n\
string sensor_id\n\
================================================================================\n\
MSG: roscpp_tutorials/MsgHeader\n\
uint64 timestamp\n\
uint64 sequence_num\n\
uint16 module_name\n\
uint16 status\n\
uint64 is_debag\n\
uint64 measured_timestamp\n\
uint8[3] version\n\
uint64 token\n\
uint64 token_timestamp\n\
string detail\n\
\n\
\n\
================================================================================\n\
MSG: roscpp_tutorials/Detection\n\
float32 upper_left_x\n\
float32 upper_left_y\n\
float32 lower_right_x\n\
float32 lower_right_y\n\
string label\n\
float32 confidence\n\
";
  }

  static const char* value(const ::roscpp_tutorials::CameraDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detections);
      stream.next(m.sensor_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::CameraDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::CameraDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::roscpp_tutorials::MsgHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detections[]" << std::endl;
    for (size_t i = 0; i < v.detections.size(); ++i)
    {
      s << indent << "  detections[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roscpp_tutorials::Detection_<ContainerAllocator> >::stream(s, indent + "    ", v.detections[i]);
    }
    s << indent << "sensor_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sensor_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_CAMERADETECTION_H
