// Generated by gencpp from file roscpp_tutorials/EpbCmd.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_EPBCMD_H
#define ROSCPP_TUTORIALS_MESSAGE_EPBCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct EpbCmd_
{
  typedef EpbCmd_<ContainerAllocator> Type;

  EpbCmd_()
    : epb_mode(0)
    , epb_value(0.0)
    , ah_mode(0)  {
    }
  EpbCmd_(const ContainerAllocator& _alloc)
    : epb_mode(0)
    , epb_value(0.0)
    , ah_mode(0)  {
  (void)_alloc;
    }



   typedef uint16_t _epb_mode_type;
  _epb_mode_type epb_mode;

   typedef float _epb_value_type;
  _epb_value_type epb_value;

   typedef uint16_t _ah_mode_type;
  _ah_mode_type ah_mode;





  typedef boost::shared_ptr< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> const> ConstPtr;

}; // struct EpbCmd_

typedef ::roscpp_tutorials::EpbCmd_<std::allocator<void> > EpbCmd;

typedef boost::shared_ptr< ::roscpp_tutorials::EpbCmd > EpbCmdPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::EpbCmd const> EpbCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::EpbCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d2c27cff63acdcb7cd94fb6be3913439";
  }

  static const char* value(const ::roscpp_tutorials::EpbCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd2c27cff63acdcb7ULL;
  static const uint64_t static_value2 = 0xcd94fb6be3913439ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/EpbCmd";
  }

  static const char* value(const ::roscpp_tutorials::EpbCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "  uint16 epb_mode\n\
  float32 epb_value\n\
  uint16 ah_mode\n\
";
  }

  static const char* value(const ::roscpp_tutorials::EpbCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.epb_mode);
      stream.next(m.epb_value);
      stream.next(m.ah_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EpbCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::EpbCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::EpbCmd_<ContainerAllocator>& v)
  {
    s << indent << "epb_mode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.epb_mode);
    s << indent << "epb_value: ";
    Printer<float>::stream(s, indent + "  ", v.epb_value);
    s << indent << "ah_mode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ah_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_EPBCMD_H
