// Generated by gencpp from file roscpp_tutorials/INSStdevRaw.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_INSSTDEVRAW_H
#define ROSCPP_TUTORIALS_MESSAGE_INSSTDEVRAW_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roscpp_tutorials/MsgHeader.h>

namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct INSStdevRaw_
{
  typedef INSStdevRaw_<ContainerAllocator> Type;

  INSStdevRaw_()
    : header()
    , measured_timestamp()
    , position_std_dev()
    , linear_velocity_std_dev()
    , orientation_std_dev()  {
      position_std_dev.assign(0.0);

      linear_velocity_std_dev.assign(0.0);

      orientation_std_dev.assign(0.0);
  }
  INSStdevRaw_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , measured_timestamp()
    , position_std_dev()
    , linear_velocity_std_dev()
    , orientation_std_dev()  {
  (void)_alloc;
      position_std_dev.assign(0.0);

      linear_velocity_std_dev.assign(0.0);

      orientation_std_dev.assign(0.0);
  }



   typedef  ::roscpp_tutorials::MsgHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef ros::Time _measured_timestamp_type;
  _measured_timestamp_type measured_timestamp;

   typedef boost::array<float, 3>  _position_std_dev_type;
  _position_std_dev_type position_std_dev;

   typedef boost::array<float, 3>  _linear_velocity_std_dev_type;
  _linear_velocity_std_dev_type linear_velocity_std_dev;

   typedef boost::array<float, 3>  _orientation_std_dev_type;
  _orientation_std_dev_type orientation_std_dev;





  typedef boost::shared_ptr< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> const> ConstPtr;

}; // struct INSStdevRaw_

typedef ::roscpp_tutorials::INSStdevRaw_<std::allocator<void> > INSStdevRaw;

typedef boost::shared_ptr< ::roscpp_tutorials::INSStdevRaw > INSStdevRawPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::INSStdevRaw const> INSStdevRawConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2b9a88dab0334b514aa627e60cfa4afb";
  }

  static const char* value(const ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2b9a88dab0334b51ULL;
  static const uint64_t static_value2 = 0x4aa627e60cfa4afbULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/INSStdevRaw";
  }

  static const char* value(const ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> >
{
  static const char* value()
  {
    return "  MsgHeader header\n\
\n\
  time measured_timestamp\n\
\n\
  float32[3] position_std_dev\n\
\n\
  float32[3] linear_velocity_std_dev\n\
\n\
  float32[3] orientation_std_dev\n\
\n\
================================================================================\n\
MSG: roscpp_tutorials/MsgHeader\n\
uint64 timestamp\n\
uint64 sequence_num\n\
uint16 module_name\n\
uint16 status\n\
uint64 is_debag\n\
uint64 measured_timestamp\n\
uint8[3] version\n\
uint64 token\n\
uint64 token_timestamp\n\
string detail\n\
\n\
";
  }

  static const char* value(const ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.measured_timestamp);
      stream.next(m.position_std_dev);
      stream.next(m.linear_velocity_std_dev);
      stream.next(m.orientation_std_dev);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct INSStdevRaw_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::INSStdevRaw_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::roscpp_tutorials::MsgHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "measured_timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.measured_timestamp);
    s << indent << "position_std_dev[]" << std::endl;
    for (size_t i = 0; i < v.position_std_dev.size(); ++i)
    {
      s << indent << "  position_std_dev[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.position_std_dev[i]);
    }
    s << indent << "linear_velocity_std_dev[]" << std::endl;
    for (size_t i = 0; i < v.linear_velocity_std_dev.size(); ++i)
    {
      s << indent << "  linear_velocity_std_dev[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.linear_velocity_std_dev[i]);
    }
    s << indent << "orientation_std_dev[]" << std::endl;
    for (size_t i = 0; i < v.orientation_std_dev.size(); ++i)
    {
      s << indent << "  orientation_std_dev[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.orientation_std_dev[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_INSSTDEVRAW_H
