// Generated by gencpp from file roscpp_tutorials/LightCmd.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_LIGHTCMD_H
#define ROSCPP_TUTORIALS_MESSAGE_LIGHTCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct LightCmd_
{
  typedef LightCmd_<ContainerAllocator> Type;

  LightCmd_()
    : beam_status(0)
    , turn_signal(0)
    , brake_light_status(0)  {
    }
  LightCmd_(const ContainerAllocator& _alloc)
    : beam_status(0)
    , turn_signal(0)
    , brake_light_status(0)  {
  (void)_alloc;
    }



   typedef uint16_t _beam_status_type;
  _beam_status_type beam_status;

   typedef uint16_t _turn_signal_type;
  _turn_signal_type turn_signal;

   typedef uint16_t _brake_light_status_type;
  _brake_light_status_type brake_light_status;





  typedef boost::shared_ptr< ::roscpp_tutorials::LightCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::LightCmd_<ContainerAllocator> const> ConstPtr;

}; // struct LightCmd_

typedef ::roscpp_tutorials::LightCmd_<std::allocator<void> > LightCmd;

typedef boost::shared_ptr< ::roscpp_tutorials::LightCmd > LightCmdPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::LightCmd const> LightCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::LightCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::LightCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::LightCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::LightCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::LightCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::LightCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::LightCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::LightCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::LightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "796bb30abdd8d1790f0c398078289e6b";
  }

  static const char* value(const ::roscpp_tutorials::LightCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x796bb30abdd8d179ULL;
  static const uint64_t static_value2 = 0x0f0c398078289e6bULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::LightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/LightCmd";
  }

  static const char* value(const ::roscpp_tutorials::LightCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::LightCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 beam_status\n\
uint16 turn_signal\n\
uint16 brake_light_status\n\
";
  }

  static const char* value(const ::roscpp_tutorials::LightCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::LightCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.beam_status);
      stream.next(m.turn_signal);
      stream.next(m.brake_light_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LightCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::LightCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::LightCmd_<ContainerAllocator>& v)
  {
    s << indent << "beam_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.beam_status);
    s << indent << "turn_signal: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.turn_signal);
    s << indent << "brake_light_status: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.brake_light_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_LIGHTCMD_H
