// Generated by gencpp from file roscpp_tutorials/MeasureState.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_MEASURESTATE_H
#define ROSCPP_TUTORIALS_MESSAGE_MEASURESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct MeasureState_
{
  typedef MeasureState_<ContainerAllocator> Type;

  MeasureState_()
    {
    }
  MeasureState_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }





  enum {
    NOT_VALID = 0u,
    NOT_STABLE = 1u,
    OK = 2u,
    VALID = 3u,
  };


  typedef boost::shared_ptr< ::roscpp_tutorials::MeasureState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::MeasureState_<ContainerAllocator> const> ConstPtr;

}; // struct MeasureState_

typedef ::roscpp_tutorials::MeasureState_<std::allocator<void> > MeasureState;

typedef boost::shared_ptr< ::roscpp_tutorials::MeasureState > MeasureStatePtr;
typedef boost::shared_ptr< ::roscpp_tutorials::MeasureState const> MeasureStateConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::MeasureState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::MeasureState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::MeasureState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::MeasureState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::MeasureState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::MeasureState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::MeasureState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::MeasureState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::MeasureState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "851926924c434a262e4e496805bf74c1";
  }

  static const char* value(const ::roscpp_tutorials::MeasureState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x851926924c434a26ULL;
  static const uint64_t static_value2 = 0x2e4e496805bf74c1ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::MeasureState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/MeasureState";
  }

  static const char* value(const ::roscpp_tutorials::MeasureState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::MeasureState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 NOT_VALID = 0\n\
uint8 NOT_STABLE = 1\n\
uint8 OK = 2\n\
uint8 VALID = 3\n\
";
  }

  static const char* value(const ::roscpp_tutorials::MeasureState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::MeasureState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MeasureState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::MeasureState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::roscpp_tutorials::MeasureState_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_MEASURESTATE_H
