// Generated by gencpp from file roscpp_tutorials/PadMessage.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_PADMESSAGE_H
#define ROSCPP_TUTORIALS_MESSAGE_PADMESSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roscpp_tutorials/MsgHeader.h>

namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct PadMessage_
{
  typedef PadMessage_<ContainerAllocator> Type;

  PadMessage_()
    : header()
    , driving_mode(0)
    , action(0)  {
    }
  PadMessage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , driving_mode(0)
    , action(0)  {
  (void)_alloc;
    }



   typedef  ::roscpp_tutorials::MsgHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint16_t _driving_mode_type;
  _driving_mode_type driving_mode;

   typedef uint16_t _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::roscpp_tutorials::PadMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::PadMessage_<ContainerAllocator> const> ConstPtr;

}; // struct PadMessage_

typedef ::roscpp_tutorials::PadMessage_<std::allocator<void> > PadMessage;

typedef boost::shared_ptr< ::roscpp_tutorials::PadMessage > PadMessagePtr;
typedef boost::shared_ptr< ::roscpp_tutorials::PadMessage const> PadMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::PadMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::PadMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::PadMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::PadMessage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::PadMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::PadMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::PadMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::PadMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::PadMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57209c4b460232070c2cd77c36838965";
  }

  static const char* value(const ::roscpp_tutorials::PadMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57209c4b46023207ULL;
  static const uint64_t static_value2 = 0x0c2cd77c36838965ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::PadMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/PadMessage";
  }

  static const char* value(const ::roscpp_tutorials::PadMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::PadMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MsgHeader header\n\
uint16 driving_mode\n\
uint16 action\n\
================================================================================\n\
MSG: roscpp_tutorials/MsgHeader\n\
uint64 timestamp\n\
uint64 sequence_num\n\
uint16 module_name\n\
uint16 status\n\
uint64 is_debag\n\
uint64 measured_timestamp\n\
uint8[3] version\n\
uint64 token\n\
uint64 token_timestamp\n\
string detail\n\
\n\
";
  }

  static const char* value(const ::roscpp_tutorials::PadMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::PadMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.driving_mode);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PadMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::PadMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::PadMessage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::roscpp_tutorials::MsgHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "driving_mode: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.driving_mode);
    s << indent << "action: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_PADMESSAGE_H
