// Generated by gencpp from file roscpp_tutorials/PredictionObstacle.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_PREDICTIONOBSTACLE_H
#define ROSCPP_TUTORIALS_MESSAGE_PREDICTIONOBSTACLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roscpp_tutorials/PerceptionObstacle.h>
#include <roscpp_tutorials/Trajectory.h>

namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct PredictionObstacle_
{
  typedef PredictionObstacle_<ContainerAllocator> Type;

  PredictionObstacle_()
    : perception_obstacle()
    , gps_timestamp()
    , predicted_period(0.0)
    , trajectories()  {
    }
  PredictionObstacle_(const ContainerAllocator& _alloc)
    : perception_obstacle(_alloc)
    , gps_timestamp()
    , predicted_period(0.0)
    , trajectories(_alloc)  {
  (void)_alloc;
    }



   typedef  ::roscpp_tutorials::PerceptionObstacle_<ContainerAllocator>  _perception_obstacle_type;
  _perception_obstacle_type perception_obstacle;

   typedef ros::Time _gps_timestamp_type;
  _gps_timestamp_type gps_timestamp;

   typedef float _predicted_period_type;
  _predicted_period_type predicted_period;

   typedef std::vector< ::roscpp_tutorials::Trajectory_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::roscpp_tutorials::Trajectory_<ContainerAllocator> >::other >  _trajectories_type;
  _trajectories_type trajectories;





  typedef boost::shared_ptr< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> const> ConstPtr;

}; // struct PredictionObstacle_

typedef ::roscpp_tutorials::PredictionObstacle_<std::allocator<void> > PredictionObstacle;

typedef boost::shared_ptr< ::roscpp_tutorials::PredictionObstacle > PredictionObstaclePtr;
typedef boost::shared_ptr< ::roscpp_tutorials::PredictionObstacle const> PredictionObstacleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "608c86386ff9a0319adf616639f65585";
  }

  static const char* value(const ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x608c86386ff9a031ULL;
  static const uint64_t static_value2 = 0x9adf616639f65585ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/PredictionObstacle";
  }

  static const char* value(const ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PerceptionObstacle perception_obstacle\n\
time gps_timestamp\n\
float32 predicted_period\n\
Trajectory[] trajectories\n\
================================================================================\n\
MSG: roscpp_tutorials/PerceptionObstacle\n\
        uint32 id 		  # obstacle ID.\n\
	Point3d position  # obstacle position in the world coordinate\n\
	# system.\n\
	float32 theta 	 # heading in the world coordinate system.\n\
	Point3d velocity  # obstacle velocity.\n\
\n\
	# Size of obstacle bounding box.\n\
	float32 length  # obstacle length.\n\
	float32 width   # obstacle width.\n\
	float32 height  # obstacle height.\n\
\n\
	# obstacle corner points\n\
	Point3d[] polygon_points \n\
	# duration of an obstacle since detection in seconds.\n\
	float32 tracking_time \n\
\n\
	uint16 obstacle_type    # obstacle type\n\
	uint16 sub_type   # obstacle sub_type\n\
	float32 gps_timestamp  # GPS time in seconds.\n\
	string type_name \n\
\n\
	float32 confidence \n\
	float32 type_confidence\n\
	bool is_static\n\
\n\
	float32 reserved_1\n\
\n\
================================================================================\n\
MSG: roscpp_tutorials/Point3d\n\
	float32 x  # in meters or m/s\n\
	float32 y  # in meters or m/s\n\
	float32 z  # height in meters or m/s\n\
================================================================================\n\
MSG: roscpp_tutorials/Trajectory\n\
float32 probability\n\
TrajectoryPoint[] trajectory_points\n\
================================================================================\n\
MSG: roscpp_tutorials/TrajectoryPoint\n\
PathPoint path_point\n\
float32 v\n\
float32 a\n\
float32 relative_time\n\
float32 da\n\
================================================================================\n\
MSG: roscpp_tutorials/PathPoint\n\
Point3d position\n\
float32 theta\n\
float32 kappa\n\
float32 s\n\
float32 dkappa\n\
float32 ddkappa\n\
";
  }

  static const char* value(const ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.perception_obstacle);
      stream.next(m.gps_timestamp);
      stream.next(m.predicted_period);
      stream.next(m.trajectories);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PredictionObstacle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::PredictionObstacle_<ContainerAllocator>& v)
  {
    s << indent << "perception_obstacle: ";
    s << std::endl;
    Printer< ::roscpp_tutorials::PerceptionObstacle_<ContainerAllocator> >::stream(s, indent + "  ", v.perception_obstacle);
    s << indent << "gps_timestamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.gps_timestamp);
    s << indent << "predicted_period: ";
    Printer<float>::stream(s, indent + "  ", v.predicted_period);
    s << indent << "trajectories[]" << std::endl;
    for (size_t i = 0; i < v.trajectories.size(); ++i)
    {
      s << indent << "  trajectories[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roscpp_tutorials::Trajectory_<ContainerAllocator> >::stream(s, indent + "    ", v.trajectories[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_PREDICTIONOBSTACLE_H
