// Generated by gencpp from file roscpp_tutorials/SimpleLatDebug.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_SIMPLELATDEBUG_H
#define ROSCPP_TUTORIALS_MESSAGE_SIMPLELATDEBUG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct SimpleLatDebug_
{
  typedef SimpleLatDebug_<ContainerAllocator> Type;

  SimpleLatDebug_()
    : lateral_error(0.0)
    , ref_heading(0.0)
    , heading(0.0)
    , heading_error(0.0)
    , heading_error_rate(0.0)
    , lateral_error_rate(0.0)
    , curvature(0.0)
    , steer_angle(0.0)
    , steer_angle_feedforward(0.0)
    , steer_angle_lateral_contribution(0.0)
    , steer_angle_lateral_rate_contribution(0.0)
    , steer_angle_heading_contribution(0.0)
    , steer_angle_heading_rate_contribution(0.0)
    , steer_angle_feedback(0.0)
    , steering_position(0.0)
    , ref_speed(0.0)
    , steer_angle_limited(0.0)
    , steer_angle_integral(0.0)
    , steer_angle_correct(0.0)
    , steer_angle_roll_compensate(0.0)
    , ref_x(0.0)
    , ref_y(0.0)
    , real_speed(0.0)
    , matrix_k1(0.0)
    , matrix_k2(0.0)
    , matrix_k3(0.0)
    , matrix_k4(0.0)
    , matched_lat_acceleration(0.0)
    , matched_lat_speed(0.0)
    , matched_lat_station(0.0)  {
    }
  SimpleLatDebug_(const ContainerAllocator& _alloc)
    : lateral_error(0.0)
    , ref_heading(0.0)
    , heading(0.0)
    , heading_error(0.0)
    , heading_error_rate(0.0)
    , lateral_error_rate(0.0)
    , curvature(0.0)
    , steer_angle(0.0)
    , steer_angle_feedforward(0.0)
    , steer_angle_lateral_contribution(0.0)
    , steer_angle_lateral_rate_contribution(0.0)
    , steer_angle_heading_contribution(0.0)
    , steer_angle_heading_rate_contribution(0.0)
    , steer_angle_feedback(0.0)
    , steering_position(0.0)
    , ref_speed(0.0)
    , steer_angle_limited(0.0)
    , steer_angle_integral(0.0)
    , steer_angle_correct(0.0)
    , steer_angle_roll_compensate(0.0)
    , ref_x(0.0)
    , ref_y(0.0)
    , real_speed(0.0)
    , matrix_k1(0.0)
    , matrix_k2(0.0)
    , matrix_k3(0.0)
    , matrix_k4(0.0)
    , matched_lat_acceleration(0.0)
    , matched_lat_speed(0.0)
    , matched_lat_station(0.0)  {
  (void)_alloc;
    }



   typedef float _lateral_error_type;
  _lateral_error_type lateral_error;

   typedef float _ref_heading_type;
  _ref_heading_type ref_heading;

   typedef float _heading_type;
  _heading_type heading;

   typedef float _heading_error_type;
  _heading_error_type heading_error;

   typedef float _heading_error_rate_type;
  _heading_error_rate_type heading_error_rate;

   typedef float _lateral_error_rate_type;
  _lateral_error_rate_type lateral_error_rate;

   typedef float _curvature_type;
  _curvature_type curvature;

   typedef float _steer_angle_type;
  _steer_angle_type steer_angle;

   typedef float _steer_angle_feedforward_type;
  _steer_angle_feedforward_type steer_angle_feedforward;

   typedef float _steer_angle_lateral_contribution_type;
  _steer_angle_lateral_contribution_type steer_angle_lateral_contribution;

   typedef float _steer_angle_lateral_rate_contribution_type;
  _steer_angle_lateral_rate_contribution_type steer_angle_lateral_rate_contribution;

   typedef float _steer_angle_heading_contribution_type;
  _steer_angle_heading_contribution_type steer_angle_heading_contribution;

   typedef float _steer_angle_heading_rate_contribution_type;
  _steer_angle_heading_rate_contribution_type steer_angle_heading_rate_contribution;

   typedef float _steer_angle_feedback_type;
  _steer_angle_feedback_type steer_angle_feedback;

   typedef float _steering_position_type;
  _steering_position_type steering_position;

   typedef float _ref_speed_type;
  _ref_speed_type ref_speed;

   typedef float _steer_angle_limited_type;
  _steer_angle_limited_type steer_angle_limited;

   typedef float _steer_angle_integral_type;
  _steer_angle_integral_type steer_angle_integral;

   typedef float _steer_angle_correct_type;
  _steer_angle_correct_type steer_angle_correct;

   typedef float _steer_angle_roll_compensate_type;
  _steer_angle_roll_compensate_type steer_angle_roll_compensate;

   typedef float _ref_x_type;
  _ref_x_type ref_x;

   typedef float _ref_y_type;
  _ref_y_type ref_y;

   typedef float _real_speed_type;
  _real_speed_type real_speed;

   typedef float _matrix_k1_type;
  _matrix_k1_type matrix_k1;

   typedef float _matrix_k2_type;
  _matrix_k2_type matrix_k2;

   typedef float _matrix_k3_type;
  _matrix_k3_type matrix_k3;

   typedef float _matrix_k4_type;
  _matrix_k4_type matrix_k4;

   typedef float _matched_lat_acceleration_type;
  _matched_lat_acceleration_type matched_lat_acceleration;

   typedef float _matched_lat_speed_type;
  _matched_lat_speed_type matched_lat_speed;

   typedef float _matched_lat_station_type;
  _matched_lat_station_type matched_lat_station;





  typedef boost::shared_ptr< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> const> ConstPtr;

}; // struct SimpleLatDebug_

typedef ::roscpp_tutorials::SimpleLatDebug_<std::allocator<void> > SimpleLatDebug;

typedef boost::shared_ptr< ::roscpp_tutorials::SimpleLatDebug > SimpleLatDebugPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::SimpleLatDebug const> SimpleLatDebugConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "128a427479b4be8a3bf5bc243cda58d6";
  }

  static const char* value(const ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x128a427479b4be8aULL;
  static const uint64_t static_value2 = 0x3bf5bc243cda58d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/SimpleLatDebug";
  }

  static const char* value(const ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 lateral_error\n\
float32 ref_heading\n\
float32 heading\n\
float32 heading_error\n\
float32 heading_error_rate\n\
float32 lateral_error_rate\n\
float32 curvature\n\
float32 steer_angle\n\
float32 steer_angle_feedforward\n\
float32 steer_angle_lateral_contribution\n\
float32 steer_angle_lateral_rate_contribution\n\
float32 steer_angle_heading_contribution\n\
float32 steer_angle_heading_rate_contribution\n\
float32 steer_angle_feedback\n\
float32 steering_position\n\
float32 ref_speed\n\
float32 steer_angle_limited\n\
float32 steer_angle_integral\n\
float32 steer_angle_correct\n\
float32 steer_angle_roll_compensate\n\
float32 ref_x\n\
float32 ref_y\n\
float32 real_speed\n\
float32 matrix_k1\n\
float32 matrix_k2\n\
float32 matrix_k3\n\
float32 matrix_k4\n\
float32 matched_lat_acceleration\n\
float32 matched_lat_speed\n\
float32 matched_lat_station\n\
";
  }

  static const char* value(const ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lateral_error);
      stream.next(m.ref_heading);
      stream.next(m.heading);
      stream.next(m.heading_error);
      stream.next(m.heading_error_rate);
      stream.next(m.lateral_error_rate);
      stream.next(m.curvature);
      stream.next(m.steer_angle);
      stream.next(m.steer_angle_feedforward);
      stream.next(m.steer_angle_lateral_contribution);
      stream.next(m.steer_angle_lateral_rate_contribution);
      stream.next(m.steer_angle_heading_contribution);
      stream.next(m.steer_angle_heading_rate_contribution);
      stream.next(m.steer_angle_feedback);
      stream.next(m.steering_position);
      stream.next(m.ref_speed);
      stream.next(m.steer_angle_limited);
      stream.next(m.steer_angle_integral);
      stream.next(m.steer_angle_correct);
      stream.next(m.steer_angle_roll_compensate);
      stream.next(m.ref_x);
      stream.next(m.ref_y);
      stream.next(m.real_speed);
      stream.next(m.matrix_k1);
      stream.next(m.matrix_k2);
      stream.next(m.matrix_k3);
      stream.next(m.matrix_k4);
      stream.next(m.matched_lat_acceleration);
      stream.next(m.matched_lat_speed);
      stream.next(m.matched_lat_station);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SimpleLatDebug_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::SimpleLatDebug_<ContainerAllocator>& v)
  {
    s << indent << "lateral_error: ";
    Printer<float>::stream(s, indent + "  ", v.lateral_error);
    s << indent << "ref_heading: ";
    Printer<float>::stream(s, indent + "  ", v.ref_heading);
    s << indent << "heading: ";
    Printer<float>::stream(s, indent + "  ", v.heading);
    s << indent << "heading_error: ";
    Printer<float>::stream(s, indent + "  ", v.heading_error);
    s << indent << "heading_error_rate: ";
    Printer<float>::stream(s, indent + "  ", v.heading_error_rate);
    s << indent << "lateral_error_rate: ";
    Printer<float>::stream(s, indent + "  ", v.lateral_error_rate);
    s << indent << "curvature: ";
    Printer<float>::stream(s, indent + "  ", v.curvature);
    s << indent << "steer_angle: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle);
    s << indent << "steer_angle_feedforward: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle_feedforward);
    s << indent << "steer_angle_lateral_contribution: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle_lateral_contribution);
    s << indent << "steer_angle_lateral_rate_contribution: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle_lateral_rate_contribution);
    s << indent << "steer_angle_heading_contribution: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle_heading_contribution);
    s << indent << "steer_angle_heading_rate_contribution: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle_heading_rate_contribution);
    s << indent << "steer_angle_feedback: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle_feedback);
    s << indent << "steering_position: ";
    Printer<float>::stream(s, indent + "  ", v.steering_position);
    s << indent << "ref_speed: ";
    Printer<float>::stream(s, indent + "  ", v.ref_speed);
    s << indent << "steer_angle_limited: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle_limited);
    s << indent << "steer_angle_integral: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle_integral);
    s << indent << "steer_angle_correct: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle_correct);
    s << indent << "steer_angle_roll_compensate: ";
    Printer<float>::stream(s, indent + "  ", v.steer_angle_roll_compensate);
    s << indent << "ref_x: ";
    Printer<float>::stream(s, indent + "  ", v.ref_x);
    s << indent << "ref_y: ";
    Printer<float>::stream(s, indent + "  ", v.ref_y);
    s << indent << "real_speed: ";
    Printer<float>::stream(s, indent + "  ", v.real_speed);
    s << indent << "matrix_k1: ";
    Printer<float>::stream(s, indent + "  ", v.matrix_k1);
    s << indent << "matrix_k2: ";
    Printer<float>::stream(s, indent + "  ", v.matrix_k2);
    s << indent << "matrix_k3: ";
    Printer<float>::stream(s, indent + "  ", v.matrix_k3);
    s << indent << "matrix_k4: ";
    Printer<float>::stream(s, indent + "  ", v.matrix_k4);
    s << indent << "matched_lat_acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.matched_lat_acceleration);
    s << indent << "matched_lat_speed: ";
    Printer<float>::stream(s, indent + "  ", v.matched_lat_speed);
    s << indent << "matched_lat_station: ";
    Printer<float>::stream(s, indent + "  ", v.matched_lat_station);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_SIMPLELATDEBUG_H
