// Generated by gencpp from file roscpp_tutorials/TrafficLightRecognitions.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_TRAFFICLIGHTRECOGNITIONS_H
#define ROSCPP_TUTORIALS_MESSAGE_TRAFFICLIGHTRECOGNITIONS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roscpp_tutorials/MsgHeader.h>
#include <roscpp_tutorials/TrafficLightRecognition.h>

namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct TrafficLightRecognitions_
{
  typedef TrafficLightRecognitions_<ContainerAllocator> Type;

  TrafficLightRecognitions_()
    : header()
    , sensor_id()
    , traffic_light_recognitions()  {
    }
  TrafficLightRecognitions_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor_id(_alloc)
    , traffic_light_recognitions(_alloc)  {
  (void)_alloc;
    }



   typedef  ::roscpp_tutorials::MsgHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef std::vector< ::roscpp_tutorials::TrafficLightRecognition_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::roscpp_tutorials::TrafficLightRecognition_<ContainerAllocator> >::other >  _traffic_light_recognitions_type;
  _traffic_light_recognitions_type traffic_light_recognitions;





  typedef boost::shared_ptr< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> const> ConstPtr;

}; // struct TrafficLightRecognitions_

typedef ::roscpp_tutorials::TrafficLightRecognitions_<std::allocator<void> > TrafficLightRecognitions;

typedef boost::shared_ptr< ::roscpp_tutorials::TrafficLightRecognitions > TrafficLightRecognitionsPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::TrafficLightRecognitions const> TrafficLightRecognitionsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26cfe27ea6b3f9d4f380aedfed7c472a";
  }

  static const char* value(const ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26cfe27ea6b3f9d4ULL;
  static const uint64_t static_value2 = 0xf380aedfed7c472aULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/TrafficLightRecognitions";
  }

  static const char* value(const ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MsgHeader header\n\
    \n\
string sensor_id\n\
    \n\
TrafficLightRecognition[] traffic_light_recognitions\n\
\n\
================================================================================\n\
MSG: roscpp_tutorials/MsgHeader\n\
uint64 timestamp\n\
uint64 sequence_num\n\
uint16 module_name\n\
uint16 status\n\
uint64 is_debag\n\
uint64 measured_timestamp\n\
uint8[3] version\n\
uint64 token\n\
uint64 token_timestamp\n\
string detail\n\
\n\
\n\
================================================================================\n\
MSG: roscpp_tutorials/TrafficLightRecognition\n\
int32 id\n\
int32 type\n\
string text\n\
int32 color\n\
float32 confidence\n\
float32 tracking_time\n\
int16 remain_times\n\
Box2d box_2d\n\
Box3d box_3d\n\
\n\
================================================================================\n\
MSG: roscpp_tutorials/Box2d\n\
  int64 x\n\
  int64 y\n\
  int64 w\n\
  int64 h\n\
\n\
================================================================================\n\
MSG: roscpp_tutorials/Box3d\n\
  Point3d position\n\
  float32 l\n\
  float32 w\n\
  float32 h\n\
\n\
================================================================================\n\
MSG: roscpp_tutorials/Point3d\n\
	float32 x  # in meters or m/s\n\
	float32 y  # in meters or m/s\n\
	float32 z  # height in meters or m/s\n\
";
  }

  static const char* value(const ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor_id);
      stream.next(m.traffic_light_recognitions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TrafficLightRecognitions_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::TrafficLightRecognitions_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::roscpp_tutorials::MsgHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sensor_id);
    s << indent << "traffic_light_recognitions[]" << std::endl;
    for (size_t i = 0; i < v.traffic_light_recognitions.size(); ++i)
    {
      s << indent << "  traffic_light_recognitions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::roscpp_tutorials::TrafficLightRecognition_<ContainerAllocator> >::stream(s, indent + "    ", v.traffic_light_recognitions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_TRAFFICLIGHTRECOGNITIONS_H
