// Generated by gencpp from file roscpp_tutorials/Transform.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_TRANSFORM_H
#define ROSCPP_TUTORIALS_MESSAGE_TRANSFORM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <roscpp_tutorials/Quaterniond.h>

namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct Transform_
{
  typedef Transform_<ContainerAllocator> Type;

  Transform_()
    : measured_timestamp(0)
    , position()
    , orientation()  {
      position.assign(0.0);
  }
  Transform_(const ContainerAllocator& _alloc)
    : measured_timestamp(0)
    , position()
    , orientation(_alloc)  {
  (void)_alloc;
      position.assign(0.0);
  }



   typedef uint64_t _measured_timestamp_type;
  _measured_timestamp_type measured_timestamp;

   typedef boost::array<double, 3>  _position_type;
  _position_type position;

   typedef  ::roscpp_tutorials::Quaterniond_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::roscpp_tutorials::Transform_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::Transform_<ContainerAllocator> const> ConstPtr;

}; // struct Transform_

typedef ::roscpp_tutorials::Transform_<std::allocator<void> > Transform;

typedef boost::shared_ptr< ::roscpp_tutorials::Transform > TransformPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::Transform const> TransformConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::Transform_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::Transform_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::Transform_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::Transform_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::Transform_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::Transform_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::Transform_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::Transform_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::Transform_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fe329204c18898ddb7b07e3a5df87908";
  }

  static const char* value(const ::roscpp_tutorials::Transform_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfe329204c18898ddULL;
  static const uint64_t static_value2 = 0xb7b07e3a5df87908ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::Transform_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/Transform";
  }

  static const char* value(const ::roscpp_tutorials::Transform_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::Transform_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 measured_timestamp\n\
float64[3] position\n\
Quaterniond orientation\n\
\n\
================================================================================\n\
MSG: roscpp_tutorials/Quaterniond\n\
float64 w\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::roscpp_tutorials::Transform_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::Transform_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.measured_timestamp);
      stream.next(m.position);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Transform_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::Transform_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::Transform_<ContainerAllocator>& v)
  {
    s << indent << "measured_timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.measured_timestamp);
    s << indent << "position[]" << std::endl;
    for (size_t i = 0; i < v.position.size(); ++i)
    {
      s << indent << "  position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.position[i]);
    }
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::roscpp_tutorials::Quaterniond_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_TRANSFORM_H
