// Generated by gencpp from file roscpp_tutorials/UltrasonicRawObject.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_ULTRASONICRAWOBJECT_H
#define ROSCPP_TUTORIALS_MESSAGE_ULTRASONICRAWOBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct UltrasonicRawObject_
{
  typedef UltrasonicRawObject_<ContainerAllocator> Type;

  UltrasonicRawObject_()
    : range(0)
    , sensor_id(0)  {
    }
  UltrasonicRawObject_(const ContainerAllocator& _alloc)
    : range(0)
    , sensor_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _range_type;
  _range_type range;

   typedef uint8_t _sensor_id_type;
  _sensor_id_type sensor_id;





  typedef boost::shared_ptr< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> const> ConstPtr;

}; // struct UltrasonicRawObject_

typedef ::roscpp_tutorials::UltrasonicRawObject_<std::allocator<void> > UltrasonicRawObject;

typedef boost::shared_ptr< ::roscpp_tutorials::UltrasonicRawObject > UltrasonicRawObjectPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::UltrasonicRawObject const> UltrasonicRawObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "828a081819a960c7eefc7bfada9a2bb6";
  }

  static const char* value(const ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x828a081819a960c7ULL;
  static const uint64_t static_value2 = 0xeefc7bfada9a2bb6ULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/UltrasonicRawObject";
  }

  static const char* value(const ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 range\n\
uint8 sensor_id\n\
";
  }

  static const char* value(const ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.range);
      stream.next(m.sensor_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct UltrasonicRawObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::UltrasonicRawObject_<ContainerAllocator>& v)
  {
    s << indent << "range: ";
    Printer<int32_t>::stream(s, indent + "  ", v.range);
    s << indent << "sensor_id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.sensor_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_ULTRASONICRAWOBJECT_H
