// Generated by gencpp from file roscpp_tutorials/Vec3d.msg
// DO NOT EDIT!


#ifndef ROSCPP_TUTORIALS_MESSAGE_VEC3D_H
#define ROSCPP_TUTORIALS_MESSAGE_VEC3D_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roscpp_tutorials
{
template <class ContainerAllocator>
struct Vec3d_
{
  typedef Vec3d_<ContainerAllocator> Type;

  Vec3d_()
    : point()  {
      point.assign(0.0);
  }
  Vec3d_(const ContainerAllocator& _alloc)
    : point()  {
  (void)_alloc;
      point.assign(0.0);
  }



   typedef boost::array<float, 3>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::roscpp_tutorials::Vec3d_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roscpp_tutorials::Vec3d_<ContainerAllocator> const> ConstPtr;

}; // struct Vec3d_

typedef ::roscpp_tutorials::Vec3d_<std::allocator<void> > Vec3d;

typedef boost::shared_ptr< ::roscpp_tutorials::Vec3d > Vec3dPtr;
typedef boost::shared_ptr< ::roscpp_tutorials::Vec3d const> Vec3dConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roscpp_tutorials::Vec3d_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roscpp_tutorials::Vec3d_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roscpp_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'roscpp_tutorials': ['/home/cui-dell/catkin_ws/src/roscpp_tutorials/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::Vec3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roscpp_tutorials::Vec3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::Vec3d_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roscpp_tutorials::Vec3d_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::Vec3d_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roscpp_tutorials::Vec3d_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roscpp_tutorials::Vec3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1fa9f5fce4bc09fb8b45732f5020cdee";
  }

  static const char* value(const ::roscpp_tutorials::Vec3d_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1fa9f5fce4bc09fbULL;
  static const uint64_t static_value2 = 0x8b45732f5020cdeeULL;
};

template<class ContainerAllocator>
struct DataType< ::roscpp_tutorials::Vec3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roscpp_tutorials/Vec3d";
  }

  static const char* value(const ::roscpp_tutorials::Vec3d_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roscpp_tutorials::Vec3d_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] point\n\
\n\
";
  }

  static const char* value(const ::roscpp_tutorials::Vec3d_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roscpp_tutorials::Vec3d_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vec3d_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roscpp_tutorials::Vec3d_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roscpp_tutorials::Vec3d_<ContainerAllocator>& v)
  {
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSCPP_TUTORIALS_MESSAGE_VEC3D_H
